// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6vssUoa_DOcXvz7bssfpMAwDg3e-3GQ',
    appId: '1:291089569879:web:16095c66dbdb10445f6b12',
    messagingSenderId: '291089569879',
    projectId: 'evoltsoft-baa8e',
    authDomain: 'evoltsoft-baa8e.firebaseapp.com',
    storageBucket: 'evoltsoft-baa8e.firebasestorage.app',
    measurementId: 'G-XV3PP74VDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWvqRSdWIIuxevmGA2nwY9nMZSWDQcaDU',
    appId: '1:291089569879:android:fc63defd4d00331e5f6b12',
    messagingSenderId: '291089569879',
    projectId: 'evoltsoft-baa8e',
    storageBucket: 'evoltsoft-baa8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq2b_0JMff8NqKaD_tpBqpaFKz6-8ge2I',
    appId: '1:291089569879:ios:7160fd10d86c99515f6b12',
    messagingSenderId: '291089569879',
    projectId: 'evoltsoft-baa8e',
    storageBucket: 'evoltsoft-baa8e.firebasestorage.app',
    iosBundleId: 'com.example.evoltsoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq2b_0JMff8NqKaD_tpBqpaFKz6-8ge2I',
    appId: '1:291089569879:ios:7160fd10d86c99515f6b12',
    messagingSenderId: '291089569879',
    projectId: 'evoltsoft-baa8e',
    storageBucket: 'evoltsoft-baa8e.firebasestorage.app',
    iosBundleId: 'com.example.evoltsoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT6vssUoa_DOcXvz7bssfpMAwDg3e-3GQ',
    appId: '1:291089569879:web:681d2bc6ca460e805f6b12',
    messagingSenderId: '291089569879',
    projectId: 'evoltsoft-baa8e',
    authDomain: 'evoltsoft-baa8e.firebaseapp.com',
    storageBucket: 'evoltsoft-baa8e.firebasestorage.app',
    measurementId: 'G-MZJLZYGFPK',
  );
}
